import { KeeperType, UserRole } from "lib/enums";

export interface LoginRequest {
  email: string;
  password: string;
}

// Generated by https://quicktype.io

export interface AddNewUserRequest {
  fullName:    string;
  email:       string;
  role:        UserRole;
  keeperType?:  KeeperType;
  phoneNumber: string;
}

