// Generated by https://quicktype.io

import { IService, IToken, IUser, IWallet } from ".";

interface BaseResponse {
  state: string;
  timestamp: number;
}

export interface PageData {
  total:       number;
  currentPage: number;
  nextPage:    null | number;
  prevPage:    null | number;
  lastPage:    number;
}
interface BasePaginationResponse<T> extends BaseResponse {
  data: T[];
  pageData:  PageData;
}

export interface LoginResponse extends BaseResponse {
  user: IUser;
  token: IToken;
}

export interface AddNewUserResponse extends BaseResponse {
  user: IUser;
  password: string;
}

export interface GetUsersResponse extends BasePaginationResponse<IUser> {}
export interface GetServicesResponse extends BasePaginationResponse<IService> {}


export interface GetDashboardStats extends BaseResponse {
  stats:     Stats;
}

export interface Stats {
  users:    Users;
  jobs:     Jobs;
  wallet:   IWallet;
  services: Services;
}

export interface Jobs {
  completed: number;
}

export interface Services {
  Cooking:  number;
  Cleaning: number;
  Trash:    number;
}

export interface Users {
  admin:  number;
  keeper: number;
  client: number;
}


 

